version: "2"

linters:
  default: standard
  enable:
    - misspell
    - gocritic
  exclusions:
    paths:
      - gen
      - api/openapi

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    paths:
      - gen
      - api/openapi
